image: node:lts-alpine@sha256:5edad160011cc8cfb69d990e9ae1cb2681c0f280178241d58eba05b5bfc34047

cache:
    paths:
        - node_modules/

stages:
    - install
    - validate
    - test

install_dependencies:
    stage: install
    script:
        - npm install

validate_feature_branch:
    stage: validate
    script:
        - npm run lint && npm run type-check
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: never
        - if: $CI_COMMIT_BRANCH
          when: on_success

test_feature_branch:
    stage: test
    script:
        - npm run test
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: never
        - if: $CI_COMMIT_BRANCH
          when: on_success
