version: "3"

services:
    nextjs:
        container_name: nextjs-skeleton
        ports:
            - 3000:3000
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        env_file:
            - .env.production
